# Generated by Django 5.2.1 on 2025-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_hash', models.CharField(max_length=6, unique=True)),
                ('url', models.URLField(unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Hit count')),
            ],
        ),
    ]
